### ISSUE TITLE
API query for Engine Listing "Last Update" values

### ISSUE THREAD

**Issue by ghost** [rapid7/nexpose-resources#2]
Anyone know where the "Last Update" values are extracted from in the Engine Listing?  These are the Version, Content and Product values as seen in the Nexpose management dashboard.  I can get the rest of the info via the API 'EngineListingRequest"..just these fields are proving elusive.

**Comment by gschneider-r7** [comment]
Take a look at the [Connection#engine_versions](http://www.rubydoc.info/gems/nexpose/Nexpose/Connection#engine_versions-instance_method) method. Under the hood it's sending an API request for ConsoleCommand with the command `version engines` and then parsing the plain-text response to capture key-value pairs. If you go to your console's administration page, then go to the "Run commands" link next to the "Troubleshooting" item (near the bottom right of the page) you can run the command `version engines` to see what the keys and values will look like - the ruby code just converts that to a hash.

There is an alternative method proposed which would parse the data from the UI endpoint instead, although it hasn't been accepted as a replacement (yet - I can't recall why). See https://github.com/rapid7/nexpose-client/pull/231 for more info on that alternative.

**Comment by ghost** [comment]
Awesome.  Cheers Gavin.  Haven't had a chance to put it to the test yet, but now that I can see where it gets the data from I should be good to go.
